# Generated by Django 6.0.5 on 2026-08-19 07:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('items', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Setting',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('initiate', 'Initiate'), ('complete', 'Complete'), ('callback', 'Callback'), ('query', 'Query'), ('verify', 'Verify'), ('refund', 'Refund')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_type', models.CharField(choices=[('mpesa_callback', 'M-Pesa Callback'), ('mpesa_result', 'M-Pesa Result'), ('mpesa_timeout', 'M-Pesa Timeout'), ('ecitizen', 'eCitizen'), ('bank', 'Bank Transfer')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment Webhook',
                'verbose_name_plural': 'Payment Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='paymentplan',
            options={'ordering': ['sort_order', 'amount'], 'verbose_name': 'Payment Plan', 'verbose_name_plural': 'Payment Plans'},
        ),
        migrations.AlterModelOptions(
            name='userpaymentaccess',
            options={'verbose_name': 'User Payment Access', 'verbose_name_plural': 'User Payment Accesses'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='bank_reference',
            new_name='checkout_request_id',
        ),
        migrations.RenameField(
            model_name='userpaymentaccess',
            old_name='access_end',
            new_name='access_end_date',
        ),
        migrations.RenameField(
            model_name='userpaymentaccess',
            old_name='access_start',
            new_name='access_start_date',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_user_id_01767a_idx',
            old_name='payments_user_id_1b771c_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_transac_2dc1cb_idx',
            old_name='payments_transac_4c44f7_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mpesa_phone_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subscription_end',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subscription_start',
        ),
        migrations.RemoveField(
            model_name='userpaymentaccess',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='userpaymentaccess',
            name='applications_remaining',
        ),
        migrations.RemoveField(
            model_name='userpaymentaccess',
            name='total_applications_allowed',
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='duration_days',
            field=models.IntegerField(default=30, help_text='Number of days access is valid'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpaymentaccess',
            name='applications_limit',
            field=models.IntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='userpaymentaccess',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userpaymentaccess',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grants', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar')], default='KES', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('ecitizen', 'eCitizen'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentplan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar')], default='KES', max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='plan_type',
            field=models.CharField(choices=[('single', 'Single Application'), ('monthly', 'Monthly Access'), ('quarterly', 'Quarterly Access'), ('annual', 'Annual Access'), ('premium', 'Premium Access')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userpaymentaccess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentaccess',
            index=models.Index(fields=['user', 'has_access'], name='payments_us_user_id_bf472a_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentaccess',
            index=models.Index(fields=['access_end_date'], name='payments_us_access__cdf0e3_idx'),
        ),
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paymentplan',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userpaymentaccess',
            table=None,
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentwebhook',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='payments.payment'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='payments_in_invoice_3fa711_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'status'], name='payments_in_user_id_a545de_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment', 'transaction_type'], name='payments_pa_payment_acaa94_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='payments_pa_created_a246c6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['webhook_type', 'processed'], name='payments_pa_webhook_103406_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['created_at'], name='payments_pa_created_f1f270_idx'),
        ),
    ]
