# Generated by Django 6.0.5 on 2026-07-14 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('employment', 'Employment Contract'), ('service', 'Service Agreement'), ('placement', 'Placement Agreement')], max_length=20)),
                ('contract_file', models.FileField(upload_to='agency_contracts/')),
                ('contract_number', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('signed', 'Signed'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='KES', max_length=10)),
                ('benefits', models.TextField(blank=True)),
                ('applicant_signed', models.BooleanField(default=False)),
                ('applicant_signed_date', models.DateTimeField(blank=True, null=True)),
                ('employer_signed', models.BooleanField(default=False)),
                ('employer_signed_date', models.DateTimeField(blank=True, null=True)),
                ('agency_signed', models.BooleanField(default=False)),
                ('agency_signed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agency_contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('license', 'License Certificate'), ('registration', 'Registration Certificate'), ('accreditation', 'Accreditation Letter'), ('tax_compliance', 'Tax Compliance Certificate'), ('other', 'Other Document')], max_length=20)),
                ('document', models.FileField(upload_to='agency_documents/')),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agency_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyRecruitmentProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('sourcing', 'Candidate Sourcing'), ('screening', 'Screening'), ('interview', 'Interview'), ('reference_check', 'Reference Check'), ('document_verification', 'Document Verification'), ('employer_submission', 'Employer Submission'), ('employer_interview', 'Employer Interview'), ('offer', 'Offer Stage'), ('visa_processing', 'Visa Processing'), ('deployment', 'Deployment'), ('completed', 'Completed')], default='sourcing', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agency_recruitment_processes',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('address', models.TextField()),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency_logos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('accreditation_documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Recruitment Agencies',
                'db_table': 'recruitment_agencies',
                'ordering': ['agency_name'],
            },
        ),
        migrations.CreateModel(
            name='AgencyApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('submitted', 'Submitted to Employer'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Extended'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('submitted_to_employer_date', models.DateTimeField(blank=True, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('offer_date', models.DateTimeField(blank=True, null=True)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agency_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
