# Generated by Django 6.0.5 on 2026-07-14 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_applications', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='agencycontract',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='agencies.agencyapplication'),
        ),
        migrations.AddField(
            model_name='agencyrecruitmentprocess',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='agencies.agencyapplication'),
        ),
        migrations.AddField(
            model_name='agencyrecruitmentprocess',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_processes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentagency',
            name='active_countries',
            field=models.ManyToManyField(blank=True, related_name='active_agencies', to='jobs.country'),
        ),
        migrations.AddField(
            model_name='recruitmentagency',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='jobs.country'),
        ),
        migrations.AddField(
            model_name='recruitmentagency',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencyrecruitmentprocess',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='agencies.recruitmentagency'),
        ),
        migrations.AddField(
            model_name='agencydocument',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agencies.recruitmentagency'),
        ),
        migrations.AddField(
            model_name='agencycontract',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='agencies.recruitmentagency'),
        ),
        migrations.AddField(
            model_name='agencyapplication',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_applications', to='agencies.recruitmentagency'),
        ),
        migrations.AddIndex(
            model_name='recruitmentagency',
            index=models.Index(fields=['agency_name'], name='recruitment_agency__50a8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentagency',
            index=models.Index(fields=['license_number'], name='recruitment_license_477dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentagency',
            index=models.Index(fields=['is_verified'], name='recruitment_is_veri_3bffc4_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentagency',
            index=models.Index(fields=['license_expiry'], name='recruitment_license_1fb32f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyapplication',
            unique_together={('agency', 'job', 'applicant')},
        ),
    ]
